import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ProtectedRoute from "@/routes/ProtectedRoute";
import { Toaster } from "sonner";
import "../globals.css";
import Appbar from "@/components/Dashboard/Appbar";
import Sidebar from "@/components/Dashboard/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ProtectedRoute>
          <Toaster />
          <div className="flex bg-slate-100">
            <Sidebar />
            <div className="min-h-screen w-full ml-2 mt-2 border bg-indigo-50 rounded-lg">
              {children}
            </div>
          </div>
        </ProtectedRoute>
      </body>
    </html>
  );
}