-- CreateEnum
CREATE TYPE "Status" AS ENUM ('PENDING', 'TRIGGERED', 'IN_PROGRESS', 'FAILED', 'SUCCESS', 'TIMED_OUT', 'CANCELLED', 'SKIPPED');

-- AlterTable
ALTER TABLE "ZapRun" ADD COLUMN     "status" "Status" NOT NULL DEFAULT 'PENDING';
