import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ProtectedRoutes from "@/components/ProtectedRoutes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.className} bg-[#fffdf9]`}>
        <Navbar />
        <ProtectedRoutes>
          {children}
        </ProtectedRoutes>
      </body>
    </html>
  );
}
